---
# Source: superset/templates/deployment-beat.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-superset-celerybeat
  namespace: default
  labels:
    app: superset-celerybeat
    chart: superset-0.12.13
    release: release-name
    heritage: Helm
spec:
  # This must be a singleton
  replicas: 1
  selector:
    matchLabels:
      app: superset-celerybeat
      release: release-name
  template:
    metadata:
      annotations:
        checksum/superset_config.py: 53d743de31670c783ea9960b0a8d0e33f32132124c7e81beab78d21a2b11bd87
        checksum/superset_bootstrap.sh: dc9a47141051ced34960c313860a55e03eb48c1fa36a0ed25c03ad60cd3b5c48
        checksum/connections: 58193508001432ce7fd8f3da42462f46ff186fc66e04b6e0010757e3e892c111
        checksum/extraConfigs: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
        checksum/extraSecrets: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
        checksum/extraSecretEnv: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
        checksum/configOverrides: 90ba04c8ebd71668617d33c6cdc549fd6e18bc5a58f0ca07f5e22e01c90c30c8
        checksum/configOverridesFiles: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
      labels:
        app: "superset-celerybeat"
        release: release-name
    spec:
      securityContext:
        runAsUser: 0
      initContainers:
      - command:
        - /bin/sh
        - -c
        - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -wait "tcp://$REDIS_HOST:$REDIS_PORT"
          -timeout 120s
        envFrom:
        - secretRef:
            name: 'release-name-superset-env'
        image: 'apache/superset:dockerize'
        imagePullPolicy: 'IfNotPresent'
        name: wait-for-postgres-redis
      containers:
        - name: "superset-celerybeat"
          image: "apache/superset:4.0.2-dev"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-c",". /app/pythonpath/superset_bootstrap.sh; celery --app=superset.tasks.celery_app:app beat --pidfile /tmp/celerybeat.pid --schedule /tmp/celerybeat-schedule"]
          env:
            - name: "SUPERSET_PORT"
              value: "8088"
          envFrom:
            - secretRef:
                name: "release-name-superset-env"
          volumeMounts:
            - name: superset-config
              mountPath: "/app/pythonpath"
              readOnly: true
          resources:
            {}
      volumes:
        - name: superset-config
          secret:
            secretName: release-name-superset-config
