---
# Source: superset/templates/secret-env.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-superset-env
  namespace: default
  labels:
    app: release-name-superset
    chart: superset-0.12.13
    release: "release-name"
    heritage: "Helm"
type: Opaque
stringData:
    REDIS_HOST: "redis"
    REDIS_USER: ""
    REDIS_PORT: "6379"
    REDIS_PROTO: "redis"
    REDIS_DB: "1"
    REDIS_CELERY_DB: "0"
    DB_HOST: "mariadb"
    DB_PORT: "3306"
    DB_USER: "superset"
    DB_PASS: "superset"
    DB_NAME: "superset"
