---
# Source: superset/templates/service-flower.yaml
apiVersion: v1
kind: Service
metadata:
  name: "release-name-superset-flower"
  namespace: default
  labels:
    app: superset
    chart: superset-0.12.13
    release: release-name
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5555
      targetPort: flower
      protocol: TCP
      name: flower
  selector:
    app: superset-flower
    release: release-name
