---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adminer-config
  labels:
    app: adminer
data:
  ADMINER_DEFAULT_SERVER: mariadb # 設置默認的 MariaDB 服務名稱
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:4.8.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: adminer-config
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 80            # Service暴露的端口
      targetPort: 8080    # Pod容器內的端口
      nodePort: 30080     # 指定NodePort（範圍30000-32767）
  type: NodePort          # 將類型改為NodePort