---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-secret
  labels:
    app: mariadb
data:
  MARIADB_DATABASE: superset
  MARIADB_USER: superset
  MARIADB_PASSWORD: superset
  MARIADB_ROOT_PASSWORD: superset

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-volume
  labels:
    type: local
    app: mariadb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/mariadb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-volume-claim
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mariadb-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadbdata
      volumes:
        - name: mariadbdata
          persistentVolumeClaim:
            claimName: mariadb-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb  # Must match Deployment's labels
  ports:
    - protocol: TCP
      port: 3306         # Service port
      targetPort: 3306   # Pod's container port
  type: ClusterIP        # Default type, for internal cluster communication
