---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-redis-config
data:
  maxmemory : 2mb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
       app: redis
    spec:
      containers:
      - name: redis
        image: redis:7
        ports:
          - containerPort: 6379
        resources:
              requests:
                   cpu: "1m"
        volumeMounts:
          - name: data
            mountPath: /redis-master-data
          - name: redis-config
            mountPath: /redis-master
      volumes:
      - name: redis-config
        configMap:
           name: my-redis-config
      - name: data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis  # 匹配 Deployment 的 labels
  ports:
    - protocol: TCP
      port: 6379         # Service 暴露的端口
      targetPort: 6379   # Pod 的 containerPort
  type: ClusterIP        # 默认类型，适用于集群内通信